name: Setup gfortran on macOS

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install gcc (provides gfortran)
        run: brew install gcc

      - name: Make gfortran available as "gfortran"
        run: |
          GF_BIN="$(ls $(brew --prefix)/bin/gfortran* 2>/dev/null | sort -V | tail -n1)"
          if [ -z "$GF_BIN" ]; then
            echo "gfortran binary not found in $(brew --prefix)/bin" >&2
            exit 1
          fi
          sudo ln -sf "$GF_BIN" /usr/local/bin/gfortran
          echo "Symlinked $GF_BIN -> /usr/local/bin/gfortran"

      - name: Verify gfortran
        run: gfortran --version
