name: Setup gfortran on macOS

on:
  workflow_dispatch:

jobs:
  setup-gfortran:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gfortran
        run: |
          brew update
          brew install gcc

      - name: Verify gfortran installation
        run: |
          gfortran --version
