name: Build and Release (macos only)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            exe_name: BaM
            test_cmd: ./BaM --version

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install gfortran (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gcc
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          cd ..
          git clone https://github.com/benRenard/miniDMSL.git miniDMSL 
          git clone https://github.com/benRenard/BMSL.git BMSL 
      - name: Call make
        run: |
          cd makefile
          make
      - name: Test executable
        run: |
          cd makefile
          ${{ matrix.test_cmd }}
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: BaM-${{ matrix.os }}
          path: makefile/${{ matrix.exe_name }}
